### PR TITLE
Fix compilation with WIN32_LEAN_AND_MEAN (through UNDEF)

### LINKED ISSUE #766: MSVC build with hidapi in-source fails with errors related to WINAPI
Image

I am currently trying to build OpenRGB with HIDAPI built into the source (due to the need to ship the `connection-callback` branch specifically without it accidentally cross-linking to anything else). I added hidapi as a submodle specifically targeting that branch, though the specific error at hand is not related to that, but if I misconfigured the submodule - it could fail the build for you so pls let me know if that's the case.

The full project is located in here: https://gitlab.com/k1-801/OpenRGB/-/tree/hotplug_standalone . The project uses QMake build system, which is not very common, and I am using a MSVC 2019 compiler. I have included the `hid.c` files for each operating system into the project source list, as well as included the header folder in the includepath. I made no compiler flags changes for hidapi. The screenshot shows the errors I'm getting.

What could be causing this? How should I go about fixing this build.

If anyone could point me towards what else to check, that'd be awesome.

Thank you all in advance and happy holidays.

### PR DESCRIPTION
**Pull request by k1-801**
Fixes #766 
This version is less complicated and just undefines the thing. The previous PR with a proper solution didn't work well with CI, trying a simpler solution.

### CODE REVIEW

File: windows/hid.c [hunk 1]
```diff
@@ -30,6 +30,11 @@
 extern "C" {
 #endif
 
+#ifdef WIN32_LEAN_AND_MEAN
+/* This define may be set by IDE/project and it breaks compilation */
```
Comment (Youw) [inline windows/hid.c]: add details in which cases compilatino is broken (apparently not always)

Comment (Youw) [reply windows/hid.c]: tried locally, maybe "not always" part in my assumption not true, but I don't really want to investigate
adjusted the comment accordingly

**Review by Youw — APPROVED** [review]
